### ISSUE TITLE
Incorrect dependencies are identified

### ISSUE THREAD

**Issue by iamrahul127** [CycloneDX/cyclonedx-dotnet#561]
Hi,
We are using [cyclonedx-dotnet](https://github.com/CycloneDX/cyclonedx-dotnet) and facing incorrect dependencies issue. 

Sample solution with two projects look like below and attached to the thread. Please note **ClassLibrary1** is **netstandard 2.0** project. Sample project [BOMIssue.zip](https://github.com/CycloneDX/cyclonedx-dotnet/files/9000640/BOMIssue.zip)

![image](https://user-images.githubusercontent.com/24877322/176169429-8a0796fb-388c-4109-9c6c-a6f76716731a.png)

Observations:

1. When I generate BOM for entire solution using dotnet CycloneDX -o . -j BOMIssue.sln following dependency is added to BOM.
`{ "ref": "pkg:nuget/NServiceBus.Newtonsoft.Json@2.3.0", "dependsOn": [ "pkg:nuget/NServiceBus@7.3.0", "pkg:nuget/Newtonsoft.Json@11.0.2" ] },`

2. When I generate BOM only for using dotnet CycloneDX -o . -j BOMIssue/BOMIssue.csproj following dependency is added to BOM.
`{ "ref": "pkg:nuget/**NServiceBus.Newtonsoft.Json@2.3.0**", "dependsOn": [ "pkg:nuget/NServiceBus@7.0.0", "pkg:nuget/**Newtonsoft.Json@13.0.1**" ] },`

I think tool is reporting incorrect dependency of **NServiceBus.Newtonsoft.Json@2.3.0** on **Newtonsoft.Json@11.0.2**. In fact **IdentityModel@4.1.1** is depending on **Newtonsoft.Json@11.0.2**
[BOMIssue.zip](https://github.com/CycloneDX/cyclonedx-dotnet/files/9000635/BOMIssue.zip)
.

Build output is correct as below.

![image](https://user-images.githubusercontent.com/24877322/176169358-f175acb5-4b5b-45ea-9897-b216e3aebec6.png)

Could you please investigate further?

**Comment by iamrahul127** [comment]
@coderpatros @verzada I have tested this with latest code you have and my reflection is this issue is fixed already. When are you planning to release latest version?

**Comment by Pvlerick** [comment]
This issue is not solved. I have a repro example here: https://github.com/Pvlerick/cyclonedx-repro-561/commit/11d87882e9630cf88f72ac5b4d0b33ae29cdd413#diff-5756cd2f62a57f43d8a6f3715ab654def4a774734c5cbaf6ae50f2d00676eac0L1099

When a reference comes implicitly from another project but the main project references a newer version of the package, that is not taken into account in the bom.

**Comment by Pvlerick** [comment]
My bad, it is actually correct since we ask cyclonedx to analyze the solution, so the dependent package could bring along the offending reference if referenced directly.
